spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.mopl.global.event.NotificationRequestedEvent

  batch:
    jdbc:
      initialize-schema: always
  mail:
    username: test@test.com
    password: test

app:
  frontend:
    base-url: http://localhost:3000
  cors:
    allowed-origins:
      - http://localhost:3000
  cookie:
    secure: false

security:
  csrf:
    disabled: true

mopl:
  jwt:
    secret: 0123456789012345678901234567890123456789
    access-token-expiry-ms: 3600000
    refresh-token-expiry-ms: 1209600000
