events {}

http {

    upstream backend {
       server modu-playlist-alb-1978007174.ap-northeast-2.elb.amazonaws.com:80;
    }

    server {

        listen 80;

        location /api/sse {
            proxy_pass http://backend;
            include proxy_headers.conf;

            # SSE 전용 설정
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            chunked_transfer_encoding on;
        }

        location / {
            proxy_pass http://backend;
            include proxy_headers.conf;
        }

        location /ws {
            proxy_pass http://backend;
            include proxy_headers.conf;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}