events {}

http {

    server {

        listen 80;


        resolver 8.8.8.8 valid=10s;
        set $backend_upstream modu-playlist-alb-1978007174.ap-northeast-2.elb.amazonaws.com:8080;

        location = /healthz {
            return 200 'ok';
        }

        location /api/sse {
            proxy_pass http://$backend_upstream;
            include proxy_headers.conf;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            chunked_transfer_encoding on;
        }

        location / {
            proxy_pass http://$backend_upstream;
            include proxy_headers.conf;
        }

        location /ws {
            proxy_pass http://$backend_upstream;
            include proxy_headers.conf;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

    }

}